---
title: Spatial Data Analysis
author: Sumendar Karupakala
date: '2017-12-04'
slug: spatial-data-analysis
output:
  html_document:
    keep_md: FALSE
    highlight: pygments
    theme: flatly
    smart: false
    toc: true
    number_sections: true
    toc_float: true
categories:
  - R
tags:
  - spatial data
  - spatial analysis
---

# Importing Techniques Used in Spatial Data Analysis 
Learning the basics of importing & exploring data in various formats in R such as **tables, Vectors & Rasters** data, then we will see how to work with this data   
for eg: 

* Setting with projection
* dealing with time variable

##Section 1
###Importing Data in Table Format
####Importing Data from Table (read.table)

```{r}
# install.packages("car")
library(car)
```

##Section 2
##Section 3
##Section 4
# Data Manipulations & Data Visualisation using Descriptive statistics
Deep understanding the basics of data analysis  
for eg:  

* exploring descrptive statistical techniques 
* plotting & manipulating spatio temporal data 
* Creation of static & interactive spatio temportal maps

##Section 5
##Section 6
##Section 7
##Section 8
##Section 9
# Working with Real life data, experiment & perform advanced data analysis

* point pattern analysis(Using crime data in UK)
* time series analysis (Wind speed data)
* geo statistical interpolation (Air polution)
* statistical & machine learning regression
  * Random forest algorithm
* cluster analysis Using Earthquake data
  * k-means algorithm
  * heirarchial clustering

##Section 10
##Section 11

##Section 12
##Section 13
##Section 14
##Section 15

http://example.com

[my link](https://sumendar.netlify.com/post/2017-12-04-spatial-data-analysis.html)
  

